name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gaming-metrics-dashboard
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './gaming-metrics-dashboard/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter (if configured)
        run: npm run lint || echo "No linter configured"
        continue-on-error: true
      
      - name: Run unit tests
        run: npm test -- --run
      
      - name: Generate coverage report
        run: npm run test:coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./gaming-metrics-dashboard/coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  build-web:
    name: Build Web Application
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./gaming-metrics-dashboard
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './gaming-metrics-dashboard/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web app
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-dist
          path: gaming-metrics-dashboard/dist/
          retention-days: 7
